# -------------------
# Build stage
# -------------------
FROM node:20-alpine AS builder
WORKDIR /app

# PNPM
RUN corepack enable && corepack prepare pnpm@latest --activate

# Instalacja zależności
COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

# Kopiowanie całego projektu
COPY . .

# Generowanie Prisma Client
RUN pnpm prisma generate

# Budowanie Next.js
RUN pnpm build

# -------------------
# Runner stage
# -------------------
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

RUN corepack enable && corepack prepare pnpm@latest --activate

# Kopiujemy wszystko potrzebne do uruchomienia produkcji
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/prisma.config.ts ./prisma.config.ts
COPY --from=builder /app/src/generated/prisma ./src/generated/prisma

EXPOSE 3000

CMD ["pnpm", "start"]