/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    skills: Skill;
    projects: Project;
    'experience-steps': ExperienceStep;
    'education-steps': EducationStep;
    certifications: Certification;
    publications: Publication;
    persons: Person;
    profiles: Profile;
    links: Link;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    skills: SkillsSelect<false> | SkillsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'experience-steps': ExperienceStepsSelect<false> | ExperienceStepsSelect<true>;
    'education-steps': EducationStepsSelect<false> | EducationStepsSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    publications: PublicationsSelect<false> | PublicationsSelect<true>;
    persons: PersonsSelect<false> | PersonsSelect<true>;
    profiles: ProfilesSelect<false> | ProfilesSelect<true>;
    links: LinksSelect<false> | LinksSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('pl' | 'en') | ('pl' | 'en')[];
  globals: {
    'about-me': AboutMe;
    'portfolio-documentation': PortfolioDocumentation;
    'core-technologies': CoreTechnology;
    'code-style': CodeStyle;
  };
  globalsSelect: {
    'about-me': AboutMeSelect<false> | AboutMeSelect<true>;
    'portfolio-documentation': PortfolioDocumentationSelect<false> | PortfolioDocumentationSelect<true>;
    'core-technologies': CoreTechnologiesSelect<false> | CoreTechnologiesSelect<true>;
    'code-style': CodeStyleSelect<false> | CodeStyleSelect<true>;
  };
  locale: 'pl' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: number;
  key:
    | 'AI'
    | 'DB'
    | 'Git'
    | 'CMS'
    | 'ORM'
    | 'WS'
    | 'GraphQL'
    | 'Print3D'
    | 'Documentation'
    | 'SalesSupport'
    | 'Microservices'
    | 'LabView'
    | 'JS'
    | 'Python'
    | 'CSharp'
    | 'CPlusPlus'
    | 'Java'
    | 'MMF2Dev'
    | 'ReactJS'
    | 'CRA'
    | 'Vite'
    | 'NextJS'
    | 'TS'
    | 'DevExtremeReact'
    | 'AntDReact'
    | 'MaterialUI'
    | 'Bootstrap'
    | 'ThreeJS'
    | 'Leaflet'
    | 'PdfMake'
    | 'YukaJS'
    | 'Zustand'
    | 'Redux'
    | 'Lodash'
    | 'SocketIO'
    | 'Zod'
    | 'SASS'
    | 'LESS'
    | 'Cypress'
    | 'Jest'
    | 'PayloadCMS'
    | 'SanityCMS'
    | 'Angular'
    | 'DevExtremeAngular'
    | 'ExpressJS'
    | 'NestJS'
    | 'NodeJS'
    | 'J5'
    | 'DotNet'
    | 'Blazor'
    | 'AntDBlazor'
    | 'PostgreSQL'
    | 'MongoDB'
    | 'SQLite'
    | 'MySQL'
    | 'Drizzle'
    | 'TypeORM'
    | 'Prisma'
    | 'AWS'
    | 'GCP'
    | 'GRPC'
    | 'VPS'
    | 'Docker'
    | 'Linux'
    | 'AGV'
    | 'CADCAM'
    | 'LAD'
    | 'SCL'
    | 'STL'
    | 'TiaPortal'
    | 'PLCProgramming'
    | 'FactoryIO'
    | 'CommunicationTCPIP'
    | 'ModbusProtocol'
    | 'IQRF'
    | 'Fanuc'
    | 'Kuka'
    | 'Eagle'
    | 'Fusion360';
  name: string;
  shortName?: string | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  name: string;
  slug: string;
  subname?: string | null;
  category: 'Mechatronics' | 'Hobby' | 'IT';
  thumbnail?: (number | null) | Media;
  links?: (number | Link)[] | null;
  startDate?: string | null;
  endDate?: string | null;
  isCurrent?: boolean | null;
  description?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  skills?: (number | Skill)[] | null;
  coreSkills?: (number | Skill)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links".
 */
export interface Link {
  id: number;
  key: string;
  label: string;
  url: string;
  isExternal: boolean;
  icon?:
    | (
        | 'accessibility'
        | 'certification'
        | 'education'
        | 'feather'
        | 'handshake'
        | 'home'
        | 'project'
        | 'publication'
        | 'settings'
        | 'tech-stack'
        | 'search'
        | 'close'
        | 'lock'
        | 'unlock'
        | 'hamburger'
        | 'build'
        | 'link'
        | 'read'
      )
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience-steps".
 */
export interface ExperienceStep {
  id: number;
  position: string;
  slug: string;
  company: string;
  location: string;
  startDate: string;
  endDate?: string | null;
  isCurrent?: boolean | null;
  employmentType:
    'FullTime' | 'HalfTime' | 'QuarterTime' | 'SelfEmployed' | 'Internship' | 'Freelance' | 'Apprenticeship';
  locationType: 'OnSite' | 'Remote' | 'Hybrid';
  description?: string | null;
  duties?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  skills?: (number | Skill)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education-steps".
 */
export interface EducationStep {
  id: number;
  institution: string;
  slug: string;
  degree?: string | null;
  projectTitle?: string | null;
  fieldOfStudy?: string | null;
  description?: string | null;
  startDate: string;
  endDate?: string | null;
  isCurrent?: boolean | null;
  grade?: number | null;
  withHonors?: boolean | null;
  skills?: (number | Skill)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: number;
  title: string;
  slug: string;
  description?: string | null;
  provider?: string | null;
  credentialID?: string | null;
  issueDate: string;
  url?: string | null;
  image?: (number | null) | Media;
  skills?: (number | Skill)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications".
 */
export interface Publication {
  id: number;
  title: string;
  slug: string;
  description: string;
  publisher: string;
  keywords?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  publishDate: string;
  url: string;
  authors?: (number | Person)[] | null;
  skills?: (number | Skill)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "persons".
 */
export interface Person {
  id: number;
  name: string;
  surname: string;
  academicDegree?:
    | (
        | 'Engineer'
        | 'MasterOfScienceInEngineering'
        | 'DoctorInEngineering'
        | 'HabilitatedDoctorInEngineering'
        | 'UniversityProfessor'
        | 'Professor'
      )
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles".
 */
export interface Profile {
  id: number;
  name: string;
  slug: string;
  orderNumber: number;
  skills?: (number | Skill)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'skills';
        value: number | Skill;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'experience-steps';
        value: number | ExperienceStep;
      } | null)
    | ({
        relationTo: 'education-steps';
        value: number | EducationStep;
      } | null)
    | ({
        relationTo: 'certifications';
        value: number | Certification;
      } | null)
    | ({
        relationTo: 'publications';
        value: number | Publication;
      } | null)
    | ({
        relationTo: 'persons';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'profiles';
        value: number | Profile;
      } | null)
    | ({
        relationTo: 'links';
        value: number | Link;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  key?: T;
  name?: T;
  shortName?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  subname?: T;
  category?: T;
  thumbnail?: T;
  links?: T;
  startDate?: T;
  endDate?: T;
  isCurrent?: T;
  description?: T;
  content?: T;
  skills?: T;
  coreSkills?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience-steps_select".
 */
export interface ExperienceStepsSelect<T extends boolean = true> {
  position?: T;
  slug?: T;
  company?: T;
  location?: T;
  startDate?: T;
  endDate?: T;
  isCurrent?: T;
  employmentType?: T;
  locationType?: T;
  description?: T;
  duties?:
    | T
    | {
        value?: T;
        id?: T;
      };
  skills?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "education-steps_select".
 */
export interface EducationStepsSelect<T extends boolean = true> {
  institution?: T;
  slug?: T;
  degree?: T;
  projectTitle?: T;
  fieldOfStudy?: T;
  description?: T;
  startDate?: T;
  endDate?: T;
  isCurrent?: T;
  grade?: T;
  withHonors?: T;
  skills?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  provider?: T;
  credentialID?: T;
  issueDate?: T;
  url?: T;
  image?: T;
  skills?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "publications_select".
 */
export interface PublicationsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  publisher?: T;
  keywords?:
    | T
    | {
        value?: T;
        id?: T;
      };
  publishDate?: T;
  url?: T;
  authors?: T;
  skills?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "persons_select".
 */
export interface PersonsSelect<T extends boolean = true> {
  name?: T;
  surname?: T;
  academicDegree?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profiles_select".
 */
export interface ProfilesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  orderNumber?: T;
  skills?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "links_select".
 */
export interface LinksSelect<T extends boolean = true> {
  key?: T;
  label?: T;
  url?: T;
  isExternal?: T;
  icon?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-me".
 */
export interface AboutMe {
  id: number;
  title: string;
  email: string;
  mobile: string;
  linkedin: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-documentation".
 */
export interface PortfolioDocumentation {
  id: number;
  title: string;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "core-technologies".
 */
export interface CoreTechnology {
  id: number;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  groups: {
    slug: string;
    title: string;
    nodes: {
      icon: number | Media;
      title: string;
      skills?: (number | Skill)[] | null;
      id?: string | null;
    }[];
    references?: string[] | null;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "code-style".
 */
export interface CodeStyle {
  id: number;
  title: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-me_select".
 */
export interface AboutMeSelect<T extends boolean = true> {
  title?: T;
  email?: T;
  mobile?: T;
  linkedin?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio-documentation_select".
 */
export interface PortfolioDocumentationSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "core-technologies_select".
 */
export interface CoreTechnologiesSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  groups?:
    | T
    | {
        slug?: T;
        title?: T;
        nodes?:
          | T
          | {
              icon?: T;
              title?: T;
              skills?: T;
              id?: T;
            };
        references?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "code-style_select".
 */
export interface CodeStyleSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}