import { Locale } from '@/i18n/locale';
import { AboutMeDTO } from '@/models/aboutMeDto';

export const aboutMe: { [locale in Locale]: AboutMeDTO } = {
  pl: {
    title: 'Cześć, z tej strony Oskar',
    email: 'oskar.szkurlat@gmail.com',
    mobile: '(+48) 789 268 680',
    linkedin: 'https://www.linkedin.com/in/oskar-szkur%C5%82at-597782305',

    content: {
      root: {
        type: 'root',
        format: '',
        indent: 0,
        version: 1,
        children: [
          {
            type: 'paragraph',
            format: '',
            indent: 0,
            version: 1,
            children: [
              {
                mode: 'normal',
                text: 'Full-stack developer specjalizujący się w React oraz TypeScript, z blisko 6-letnim komercyjnym doświadczeniem w tworzeniu aplikacji webowych. Moim głównym obszarem specjalizacji jest nowoczesny Front-end, w ramach którego budowałem i rozwijałem aplikacje od podstaw oraz dostarczałem rozwiązania dla klientów z sektorów przemysłowego, bankowego i publicznego.',
                type: 'text',
                style: '',
                detail: 0,
                format: 0,
                version: 1,
              },
            ],
            direction: null,
            textStyle: '',
            textFormat: 0,
          },
          {
            type: 'paragraph',
            format: '',
            indent: 0,
            version: 1,
            children: [
              {
                mode: 'normal',
                text: 'React i TypeScript są dla mnie technologiami pierwszego wyboru, ale potrafię dostosować się do korzystania z technologii określonej w danym projekcie. W trakcie pracy komercyjnej miałem również okazję pracować z technologiami takimi jak Angular, Blazor, .NET, REST API oraz relacyjnymi bazami danych SQL.',
                type: 'text',
                style: '',
                detail: 0,
                format: 0,
                version: 1,
              },
            ],
            direction: null,
            textStyle: '',
            textFormat: 0,
          },
          {
            type: 'paragraph',
            format: '',
            indent: 0,
            version: 1,
            children: [
              {
                mode: 'normal',
                text: 'Poza pracą zawodową stale rozwijam swoje kompetencje poprzez realizację własnych projektów oraz samodzielną naukę. Korzystam z technologii takich jak Nest.js, Next.js, Node.js, Express.js, PostgreSQL, MySQL, SQLite oraz z innych narzędzi z ekosystemu JavaScript. Pozwala mi to systematycznie poszerzać moje możliwości Full-stack poza technologie wykorzystywane na co dzień.',
                type: 'text',
                style: '',
                detail: 0,
                format: 0,
                version: 1,
              },
            ],
            direction: null,
            textStyle: '',
            textFormat: 0,
          },
          {
            type: 'paragraph',
            format: '',
            indent: 0,
            version: 1,
            children: [
              {
                mode: 'normal',
                text: 'Mój inżynierski tok rozumowania wywodzi się z mechatroniki. Zanim rozpocząłem karierę jako software developer, pracowałem w obszarze automatyki przemysłowej, gdzie zajmowałem się zaawansowanym programowaniem sterowników PLC Siemens. Połączenie doświadczenia z zakresu programowania, automatyki, elektroniki oraz projektowania systemów pozwala mi spojrzeć na problemy techniczne z szerszej perspektywy i tworzyć bardziej kompleksowe rozwiązania.',
                type: 'text',
                style: '',
                detail: 0,
                format: 0,
                version: 1,
              },
            ],
            direction: null,
            textStyle: '',
            textFormat: 0,
          },
          {
            type: 'paragraph',
            format: '',
            indent: 0,
            version: 1,
            children: [
              {
                mode: 'normal',
                text: 'Technologia jest moją pasją od dzieciństwa. Tworzenie aplikacji webowych, programowanie mikroprocesorów, projektowanie układów elektronicznych, budowa własnych rozwiązań IoT czy modelowanie elementów 3D to obszary, które pozwalają mi przekuwać pomysły w rzeczywiste i praktyczne produkty.',
                type: 'text',
                style: '',
                detail: 0,
                format: 0,
                version: 1,
              },
            ],
            direction: null,
            textStyle: '',
            textFormat: 0,
          },
        ],
        direction: null,
      },
    },
  },

  en: {
    title: "Hello, I'm Oskar",
    email: 'oskar.szkurlat@gmail.com',
    mobile: '(+48) 789 268 680',
    linkedin: 'https://www.linkedin.com/in/oskar-szkur%C5%82at-597782305',

    content: {
      root: {
        type: 'root',
        format: '',
        indent: 0,
        version: 1,
        children: [
          {
            type: 'paragraph',
            format: '',
            indent: 0,
            version: 1,
            children: [
              {
                mode: 'normal',
                text: 'Full-stack developer specializing in React and TypeScript with nearly 6 years of commercial experience building web applications. My primary focus is modern front-end development, where I have built and maintained web applications from scratch, worked on enterprise-scale systems, and delivered solutions for industrial, banking, and public-sector clients.',
                type: 'text',
                style: '',
                detail: 0,
                format: 0,
                version: 1,
              },
            ],
            direction: null,
            textStyle: '',
            textFormat: 0,
          },
          {
            type: 'paragraph',
            format: '',
            indent: 0,
            version: 1,
            children: [
              {
                mode: 'normal',
                text: 'React and TypeScript are my strongest technologies, but I am comfortable working across the entire application stack whenever a project requires it. Over the years, I have also worked commercially with Angular, Blazor, .NET, REST APIs, and SQL databases.',
                type: 'text',
                style: '',
                detail: 0,
                format: 0,
                version: 1,
              },
            ],
            direction: null,
            textStyle: '',
            textFormat: 0,
          },
          {
            type: 'paragraph',
            format: '',
            indent: 0,
            version: 1,
            children: [
              {
                mode: 'normal',
                text: 'Beyond my commercial experience, I continuously broaden my technical skills through personal projects and independent learning. I have worked with technologies such as Nest.js, Next.js, Node.js, Express.js, PostgreSQL, MySQL, SQLite, and other technologies from the JavaScript ecosystem. This allows me to continuously expand my full-stack capabilities beyond the technology stack used in my daily work.',
                type: 'text',
                style: '',
                detail: 0,
                format: 0,
                version: 1,
              },
            ],
            direction: null,
            textStyle: '',
            textFormat: 0,
          },
          {
            type: 'paragraph',
            format: '',
            indent: 0,
            version: 1,
            children: [
              {
                mode: 'normal',
                text: 'My engineering background is rooted in mechatronics. Before becoming a software developer, I worked with industrial automation and Siemens PLC systems at advanced level. This combination of software engineering, automation, electronics, and system design gives me a broader perspective when solving technical problems.',
                type: 'text',
                style: '',
                detail: 0,
                format: 0,
                version: 1,
              },
            ],
            direction: null,
            textStyle: '',
            textFormat: 0,
          },
          {
            type: 'paragraph',
            format: '',
            indent: 0,
            version: 1,
            children: [
              {
                mode: 'normal',
                text: 'Technology has been my passion since childhood. Whether building web applications, programming embedded devices, designing electronic circuits, creating IoT systems, or developing 3D-printable solutions, I enjoy transforming ideas into reliable and practical products.',
                type: 'text',
                style: '',
                detail: 0,
                format: 0,
                version: 1,
              },
            ],
            direction: null,
            textStyle: '',
            textFormat: 0,
          },
        ],
        direction: null,
      },
    },
  },
};
