import type { DefaultTypedEditorState } from '@payloadcms/richtext-lexical';

export const codeStyleContentPL: DefaultTypedEditorState = {
  root: {
    type: 'root',
    format: '',
    indent: 0,
    version: 1,
    children: [
      {
        type: 'paragraph',
        format: '',
        indent: 0,
        version: 1,
        children: [
          {
            mode: 'normal',
            text: 'Kod tworzę z myślą o jego dalszym rozwoju, a nie tylko o rozwiązaniu bieżącego problemu. Traktuję każdy komponent jak element biblioteki — powinien mieć jasno określoną odpowiedzialność, być w pełni typowany, niezależny od konkretnego repozytorium i możliwy do wykorzystania w innym projekcie bez przepisywania jego logiki.',
            type: 'text',
            style: '',
            detail: 0,
            format: 0,
            version: 1,
          },
        ],
        direction: null,
        textStyle: '',
        textFormat: 0,
      },
      {
        type: 'paragraph',
        format: '',
        indent: 0,
        version: 1,
        children: [
          {
            mode: 'normal',
            text: 'W każdym projekcie stosuję spójny standard organizacji kodu. Oddzielam komponenty od logiki, modeli, DTO, danych, serwisów i stylów, a strukturę folderów dostosowuję jedynie w zakresie wymaganym przez konkretny framework. Dbam również o konsekwentne nazewnictwo, czytelność kodu oraz zasadę, że jego struktura powinna być zrozumiała bez konieczności zagłębiania się w implementację.',
            type: 'text',
            style: '',
            detail: 0,
            format: 0,
            version: 1,
          },
        ],
        direction: null,
        textStyle: '',
        textFormat: 0,
      },
      {
        type: 'paragraph',
        format: '',
        indent: 0,
        version: 1,
        children: [
          {
            mode: 'normal',
            text: 'TypeScript wykorzystuję maksymalnie — unikam ',
            type: 'text',
            style: '',
            detail: 0,
            format: 0,
            version: 1,
          },
          {
            mode: 'normal',
            text: 'any',
            type: 'text',
            style: '',
            detail: 0,
            format: 16,
            version: 1,
          },
          {
            mode: 'normal',
            text: ', nie stosuję niepotrzebnych rzutowań i świadomie definiuję typy również tam, gdzie kompilator mógłby je wywnioskować. Dzięki temu kod jest bardziej przewidywalny, łatwiejszy w refaktoryzacji i bezpieczniejszy w dalszym rozwoju.',
            type: 'text',
            style: '',
            detail: 0,
            format: 0,
            version: 1,
          },
        ],
        direction: null,
        textStyle: '',
        textFormat: 0,
      },
      {
        type: 'paragraph',
        format: '',
        indent: 0,
        version: 1,
        children: [
          {
            mode: 'normal',
            text: 'Każdy projekt konfiguruję również pod kątem automatycznej kontroli jakości, wykorzystując m.in. Prettiera, ESLinta i type-checking. Stosuję ten sam sposób organizacji pracy z Gitem, nazewnictwem branchy oraz dokumentowaniem uniwersalnych komponentów.',
            type: 'text',
            style: '',
            detail: 0,
            format: 0,
            version: 1,
          },
        ],
        direction: null,
        textStyle: '',
        textFormat: 0,
      },
      {
        type: 'paragraph',
        format: '',
        indent: 0,
        version: 1,
        children: [
          {
            mode: 'normal',
            text: 'Szczególną uwagę przykładam również do warstwowania aplikacji. Przykładem są tworzone przeze mnie rozbudowane komponenty DataGrid, w których wspólna warstwa UI może współpracować z niezależnymi providerami danych, np. OData lub danymi statycznymi przetwarzanymi po stronie klienta.',
            type: 'text',
            style: '',
            detail: 0,
            format: 0,
            version: 1,
          },
        ],
        direction: null,
        textStyle: '',
        textFormat: 0,
      },
      {
        type: 'paragraph',
        format: '',
        indent: 0,
        version: 1,
        children: [
          {
            mode: 'normal',
            text: 'Dzięki temu, niezależnie od tego, czy pracuję z Reactem, Next.js, Vite czy inną technologią, zachowuję ten sam sposób myślenia o kodzie: ',
            type: 'text',
            style: '',
            detail: 0,
            format: 0,
            version: 1,
          },
          {
            mode: 'normal',
            text: 'czytelność, reużywalność, silne typowanie, separacja odpowiedzialności i konsekwencja',
            type: 'text',
            style: '',
            detail: 0,
            format: 1,
            version: 1,
          },
          {
            mode: 'normal',
            text: '.',
            type: 'text',
            style: '',
            detail: 0,
            format: 0,
            version: 1,
          },
        ],
        direction: null,
        textStyle: '',
        textFormat: 0,
      },
    ],
    direction: null,
  },
};

export const codeStyleContentEN: DefaultTypedEditorState = {
  root: {
    type: 'root',
    format: '',
    indent: 0,
    version: 1,
    children: [
      {
        type: 'paragraph',
        format: '',
        indent: 0,
        version: 1,
        children: [
          {
            mode: 'normal',
            text: 'I write code with its long-term development in mind, rather than simply solving the problem at hand. I treat every component as a part of a library — it should have a clearly defined responsibility, be fully typed, remain independent of the specific repository, and be reusable in another project without rewriting its core logic.',
            type: 'text',
            style: '',
            detail: 0,
            format: 0,
            version: 1,
          },
        ],
        direction: null,
        textStyle: '',
        textFormat: 0,
      },
      {
        type: 'paragraph',
        format: '',
        indent: 0,
        version: 1,
        children: [
          {
            mode: 'normal',
            text: 'Across all my projects, I follow a consistent coding standard. I separate components from logic, models, DTOs, data, services, and styles, while adapting the folder structure only where required by the framework being used. I also focus on consistent naming, readability, and making the structure of the code understandable without having to dive into its implementation.',
            type: 'text',
            style: '',
            detail: 0,
            format: 0,
            version: 1,
          },
        ],
        direction: null,
        textStyle: '',
        textFormat: 0,
      },
      {
        type: 'paragraph',
        format: '',
        indent: 0,
        version: 1,
        children: [
          {
            mode: 'normal',
            text: 'I make extensive use of TypeScript — avoiding ',
            type: 'text',
            style: '',
            detail: 0,
            format: 0,
            version: 1,
          },
          {
            mode: 'normal',
            text: 'any',
            type: 'text',
            style: '',
            detail: 0,
            format: 16,
            version: 1,
          },
          {
            mode: 'normal',
            text: ', unnecessary type assertions, and relying on explicit types even in cases where the compiler could infer them. This makes the code more predictable, easier to refactor, and safer to maintain as the project evolves.',
            type: 'text',
            style: '',
            detail: 0,
            format: 0,
            version: 1,
          },
        ],
        direction: null,
        textStyle: '',
        textFormat: 0,
      },
      {
        type: 'paragraph',
        format: '',
        indent: 0,
        version: 1,
        children: [
          {
            mode: 'normal',
            text: 'Every project is also configured with automated quality checks, including Prettier, ESLint, and type checking. I follow consistent conventions for Git workflows, branch naming, and documentation of reusable components.',
            type: 'text',
            style: '',
            detail: 0,
            format: 0,
            version: 1,
          },
        ],
        direction: null,
        textStyle: '',
        textFormat: 0,
      },
      {
        type: 'paragraph',
        format: '',
        indent: 0,
        version: 1,
        children: [
          {
            mode: 'normal',
            text: 'I also pay particular attention to application layering. A good example is the advanced DataGrid components I have built, where a shared UI layer can work with independent data providers, such as OData or static data processed on the client side.',
            type: 'text',
            style: '',
            detail: 0,
            format: 0,
            version: 1,
          },
        ],
        direction: null,
        textStyle: '',
        textFormat: 0,
      },
      {
        type: 'paragraph',
        format: '',
        indent: 0,
        version: 1,
        children: [
          {
            mode: 'normal',
            text: 'This approach allows me to maintain the same way of thinking about code regardless of whether I am working with React, Next.js, Vite, or another technology: ',
            type: 'text',
            style: '',
            detail: 0,
            format: 0,
            version: 1,
          },
          {
            mode: 'normal',
            text: 'readability, reusability, strong typing, separation of concerns, and consistency',
            type: 'text',
            style: '',
            detail: 0,
            format: 1,
            version: 1,
          },
          {
            mode: 'normal',
            text: '.',
            type: 'text',
            style: '',
            detail: 0,
            format: 0,
            version: 1,
          },
        ],
        direction: null,
        textStyle: '',
        textFormat: 0,
      },
    ],
    direction: null,
  },
};
