export enum CoreTechnologiesSlug {
  Git = 'git',
  UiDesign = 'ui-design',
  TasksAndDocs = 'tasks-and-docs',
  JSLanguages = 'javascript-languages',
  FrontendFrameworks = 'front-end-frameworks',
  BackendFrameworks = 'back-end-frameworks',
  CssExtensions = 'css-extensions',
  FrontendTesting = 'front-end-testing',
  BackendTesting = 'back-end-testing',
  UiComponents = 'ui-components',
  BuildTools = 'build-tools',
  DeveloperTools = 'developer-tools',
  GlobalStates = 'global-states',
  CoreLibraries = 'core-libraries',
  Databases = 'databases',
  Orm = 'orm',
  Cms = 'cms',
}
