export enum CacheName {
  SkillAggregates = 'skill-agregates',
  Certifications = 'certifications',
  EducationSteps = 'education-steps',
  ExperienceSteps = 'experience-steps',
  Profiles = 'profiles',
  Project = 'project',
  Projects = 'projects',
  Publications = 'publications',
  Skills = 'skills',
  AboutMe = 'about-me',
  CodeStyle = 'code-style',
  CoreTechnologies = 'core-technologies',
  PortfolioDocumentation = 'portfolio-documentation',
}
