import type { Prisma } from "@/app/generated/prisma/client";

import { SkillKey } from "@/app/generated/prisma/client";

export const skills: Prisma.SkillCreateInput[] = [
	{ key: SkillKey.AGV },
	{ key: SkillKey.AI },
	{ key: SkillKey.AWS },
	{ key: SkillKey.Angular },
	{ key: SkillKey.AntDBlazor },
	{ key: SkillKey.AntDReact },
	{ key: SkillKey.Blazor },
	{ key: SkillKey.Bootstrap },
	{ key: SkillKey.CADCAM },
	{ key: SkillKey.CPlusPlus },
	{ key: SkillKey.CRA },
	{ key: SkillKey.CSharp },
	{ key: SkillKey.CommunicationTCPIP },
	{ key: SkillKey.DevExtremeAngular },
	{ key: SkillKey.DevExtremeReact },
	{ key: SkillKey.Docker },
	{ key: SkillKey.DotNet },
	{ key: SkillKey.Eagle },
	{ key: SkillKey.ExpressJS },
	{ key: SkillKey.FactoryIO },
	{ key: SkillKey.Fanuc },
	{ key: SkillKey.Fusion360 },
	{ key: SkillKey.GCP },
	{ key: SkillKey.GRPC },
	{ key: SkillKey.GraphQL },
	{ key: SkillKey.IQRF },
	{ key: SkillKey.J5 },
	{ key: SkillKey.Java },
	{ key: SkillKey.Kuka },
	{ key: SkillKey.LAD },
	{ key: SkillKey.LabView },
	{ key: SkillKey.Leaflet },
	{ key: SkillKey.Linux },
	{ key: SkillKey.MMF2Dev },
	{ key: SkillKey.MaterialUI },
	{ key: SkillKey.Microservices },
	{ key: SkillKey.ModbusProtocol },
	{ key: SkillKey.MongoDB },
	{ key: SkillKey.NestJS },
	{ key: SkillKey.NextJS },
	{ key: SkillKey.NodeJS },
	{ key: SkillKey.PLCProgramming },
	{ key: SkillKey.PdfMake },
	{ key: SkillKey.PostgreSQL },
	{ key: SkillKey.Print3D },
	{ key: SkillKey.Python },
	{ key: SkillKey.ReactJS },
	{ key: SkillKey.Redux },
	{ key: SkillKey.SCL },
	{ key: SkillKey.SQLite },
	{ key: SkillKey.STL },
	{ key: SkillKey.Sanity },
	{ key: SkillKey.TS },
	{ key: SkillKey.ThreeJS },
	{ key: SkillKey.TiaPortal },
	{ key: SkillKey.VPS },
	{ key: SkillKey.Vite },
	{ key: SkillKey.YukaJS },
	{ key: SkillKey.Zustand },
];