export enum CertificationSlug {
  NestJsMicroservicesScaleableBackend = 'nestjs-microservices-build-and-deploy-a-scaleable-backend',
  NestJsUltimateMasterclass = 'master-nestjs-ultimate-masterclass-2025',
  BlazorDeepDiveDotNet8 = 'blazor-deep-dive-from-beginner-to-advanced-in-dot-net-8',
  DeployNodeJsOnVps = 'deploying-a-node-js-application-on-a-vps-server',
  PostgreSqlDatabaseDesign = 'postgre-sql-database-design',
  HowToEarnFromWebsites = 'how-to-earn-from-websites-and-work-as-a-freelancer',
  NodeJsCompleteCourse = 'node-js-complete-course',
  ReactJsCompleteCourse = 'react-js-complete-course',
  SiemensS71500Advanced = 'siemens-simatic-s7-1500-programming-advanced-course',
  ModernMethodsOfPlcProgramming = 'modern-methods-of-plc-programming',
  IqrfWirelessProgramming = 'programming-and-networking-using-iqrf-wireless-technology',
  SimaticS7PlcProgramming = 'programming-simatic-s7-plc-controllers-and-designing-process-visualizations',
  MtsCncCadCam = 'programming-machine-tools-in-mts-sytem-cnc-cad-cam',
  Bootstrap4FromScratch = 'bootstrap-4-from-scratch',
  IntroductionToJavascript = 'introduction-to-javascript',
  EverestInternship = 'internship-in-the-project-i-have-a-profession-i-have-a-job-in-the-region',
  PLCProgrammingAndDesigningProcessVisualizations = 'programming-simatic-s7-plc-controllers-and-designing-process-visualizations',
  ProgrammingMachineToolsInMTSSystemCNC = 'programming-machine-tools-in-mts-system–cnc-cad-cam',
}
