export enum ProjectSlug {
  ProductionSystemUtilizingAGV = 'production-system-utilizing-agv',
  AmaranthusAGVPlatform = 'amaranthus-agv-platform',
  ElectrohydraulicSystemControl = 'electrohydraulic-system-control',
  ControlOfAGVGestureVoice = 'control-of-agv-based-on-gesture-recognition-and-voice-analysis',
  SmartTerrarium = 'smart-terrarium',
  SmartRollerShutter = 'smart-roller-shutter',
  CurriculumVitaeGenerator = 'curriculum-vitae-generator',
  ArtisticLanguageNurseryLittleAcademy = 'artistic-and-language-nursery-little-academy',
  InvoiceGeneratorV1 = 'invoice-generator-v1',
  FindingPathAI = 'finding-path-ai',
  ApplicationBinder = 'application-binder',
  LedControllerViaUSB = 'led-controller-via-usb',
  PilsudskiPalaceSmartHome = 'pilsudski-palace-smart-home',
  PilsudskiPalaceProjectAndRealization = 'pilsudski-palace-project-and-realization',
}
